### ISSUE TITLE
housekeeping

### ISSUE THREAD

**Issue by paulfears** [paulfears/StellarSnap#49]
Create a Canary Branch. Merge current Branches and deploy to NPM. Set SDF as the code owner. 👍

**Comment by ooochoche** [comment]
@paulfears Please is this still available?

**Comment by Joy-Adah** [comment]
Hi @paulfears I'd love to work on this. Can I be assigned please?

**Comment by paulfears** [comment]
new branch created STellar is now code owner upon contact
