### ISSUE TITLE
Great Documentation

### ISSUE THREAD

**Issue by paulfears** [paulfears/StellarSnap#52]
I will write a great documentation page on the metastellar.io website.

**Comment by Naomi-Gift** [comment]
@paulfears Can I work on this ?
I am a web3 developer/ Technical writer
I have experience in a lot of open source contributions especially in making Documentation
Here are some of the merged docs I’ve written
Flex-NFT-Marketplace/Flex-Marketplace-Contract@fc28412
https://hackmd.io/@xZ4BOZ5TTTy1I0ZQHXFOkg/rkFBcGgAC

**Comment by Benjtalkshow** [comment]
Hello @paulfears ,
I would really love to work on this task

**Comment by Calebux** [comment]
@paulfears This is the issue, i can jump on it
