### ISSUE TITLE
Make a Practical Readme

### ISSUE THREAD

**Issue by paulfears** [paulfears/StellarSnap#56]
I will write a detailed readme, including how to call stellar-wallet functions from other MM snaps. This will allow other Stellar applications to launch directly to MM without the need for a code audit. As well as creating a universal standard for doing such a thing.

**Comment by Naomi-Gift** [comment]
@paulfears can I work on this?

**Comment by od-hunter** [comment]
Hi @paulfears , can I be assigned this please? I’m ready to work.

**Comment by vickiddev** [comment]
hey @paulfears i'm a frontend dev and a technical writer and would love to take on this issue

**Comment by Oshioke-Salaki** [comment]
Please can I do this?
